name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs GitHub's Super Linter and excludes unwanted files
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: 'src/.*\.ts|src/.*\.js'  # Only lint .ts and .js files in the src folder
          FILTER_REGEX_EXCLUDE: '.*\.(sql|md|json|yml|yaml|log)$|.*(node_modules|dist|prisma)/'  # Exclude SQL, markdown, JSON, node_modules, dist, and prisma folders
